# Generated by Django 5.1.7 on 2025-04-11 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="battery_capacity",
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(default="null", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="cores",
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="cpu",
            field=models.CharField(default="Notdefined", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="delivery_info",
            field=models.CharField(default="Notdefined", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="front_camera",
            field=models.CharField(default="Notdefined", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="main_camera",
            field=models.CharField(default="Notdefined", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="pixel_density",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="screen_refresh_rate",
            field=models.IntegerField(default=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="screen_resolution",
            field=models.CharField(default="Notdefined", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="screen_size",
            field=models.DecimalField(decimal_places=2, default=12, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="warranty",
            field=models.CharField(default="Notdefined", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="store.product",
            ),
        ),
        migrations.CreateModel(
            name="ProductColors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=100)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("128GB", "128GB"),
                            ("256GB", "256GB"),
                            ("512GB", "512GB"),
                            ("1TB", "1TB"),
                        ],
                        default="128GB",
                        max_length=10,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
            ],
        ),
    ]
