# Generated by Django 5.1.7 on 2025-04-11 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_battery_capacity_product_brand_product_cores_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcolors",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="colors",
                to="store.product",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="productstorage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="storage",
                to="store.product",
            ),
        ),
    ]
