# Generated by Django 5.1.7 on 2025-04-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_productcolors_product_alter_productimage_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="last_update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
